sudo: false
language: node_js
node_js:
- '11.2.0'
cache:
  directories:
  - node_modules
branches:
  only:
  - source
notifications:
  email: false
script:
- NODE_ENV=production npm run export
- bash ./fix_github_assets_prefix.sh
before_script:
- npm prune
deploy:
  provider: pages
  local-dir: out
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  target-branch: master
  on:
    branch: source
