sudo: false
language: node_js
node_js:
- '11.2.0'
cache:
  directories:
  - node_modules
branches:
  only:
  - source
notifications:
  email: false
script:
- npm run export
before_script:
- npm prune
after_success:
- bash ./scripts/deploy.sh
